name: PHP lint & test

concurrency: ${{ github.workflow }}
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        php: ['7.2', '7.4', '8.1', '8.2', '8.3']

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v3
    
    - name: Cache Node.js packages
      id: node-cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php${{ matrix.php }}-

    - name: Install node dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer update --prefer-dist --no-progress -n
      
    - name: PHP Lint
      run: node_modules/.bin/grunt phpcs
      
    - name: PHP Unit Tests
      run: node_modules/.bin/grunt phpunit
      env:
        UNIVAPAY_PHP_TEST_ENDPOINT: https://api.gyro-n.money
        UNIVAPAY_PHP_TEST_SECRET: ${{ secrets.UNIVAPAY_PHP_TEST_SECRET }}
        UNIVAPAY_PHP_TEST_TOKEN: ${{ secrets.UNIVAPAY_PHP_TEST_TOKEN }}
