name: PHP lint & test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js environment
      uses: actions/setup-node@v2-beta
    
    - name: Cache Node.js packages
      id: node-cache
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '5.6'

    - name: Validate composer.json and composer.lock
      run: composer validate
      
    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install node dependencies
      if: steps.node-cache.outputs.cache-hit != 'true'
      run: npm install

    - name: Install composer dependencies
      if: steps.composer-cache.outputs.cache-hit != 'true'
      run: composer install --prefer-dist --no-progress -n
      
    - name: PHP Lint
      run: node_modules/.bin/grunt phpcs
      
    - name: PHP Unit Tests
      run: node_modules/.bin/grunt phpunit
      env:
        UNIVAPAY_PHP_TEST_ENDPOINT: https://api.gyro-n.money
        UNIVAPAY_PHP_TEST_SECRET: ${{ secrets.UNIVAPAY_PHP_TEST_SECRET }}
        UNIVAPAY_PHP_TEST_TOKEN: ${{ secrets.UNIVAPAY_PHP_TEST_TOKEN }}
